---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'cfssl version'
      ansible.builtin.command: /usr/local/bin/cfssl version
      changed_when: false
      register: cfssl_test_output
    - name: Output of 'cfssl version'
      ansible.builtin.debug:
        msg: '{{ cfssl_test_output.stdout }}'
