---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/cfssl version
      register: cfssl_test_output
    - name: cfssl version
      debug:
        msg: '{{ cfssl_test_output.stdout }}'
