---
- name: Mkdir -p {{ cfssl_install_dir }}...
  become: true
  become_user: root
  ansible.builtin.file:
    path: '{{ cfssl_install_dir }}'
    state: directory
    mode: '755'

- name: Downloading binaries from {{ cfssl_url_prefix }}...
  become: true
  become_user: root
  with_items: '{{ cfssl_binaries }}'
  ansible.builtin.get_url:
    url: '{{ cfssl_url_prefix }}/{{ item }}_{{ cfssl_ver }}_{{ cfssl_platform }}'
    dest: '{{ cfssl_install_dir }}/{{ item }}'
    checksum: '{{ cfssl_checksums[cfssl_ver][item][cfssl_platform] }}'
    mode: '755'

- name: Linking to binaries in {{ cfssl_install_dir }} from {{ cfssl_install_target }}...
  become: true
  become_user: root
  with_items: '{{ cfssl_binaries }}'
  ansible.builtin.file:
    src: '{{ cfssl_install_dir }}/{{ item }}'
    dest: '{{ cfssl_install_target }}/{{ item }}'
    state: link
